import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { Suspense, lazy } from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { SpeedInsights } from "@vercel/speed-insights/react";
import { Analytics } from "@vercel/analytics/react";
import SongList from "./pages/SongList";
import "./styles/global.css";
const SongDetail = lazy(() => import("./pages/SongDetail"));
const ChartDetail = lazy(() => import("./pages/ChartDetail"));
const Megamix = lazy(() => import("./pages/Megamix"));
const AdminLayout = lazy(() => import("./pages/admin/AdminLayout"));
const AdminSongList = lazy(() => import("./pages/admin/AdminSongList"));
const AdminSongEdit = lazy(() => import("./pages/admin/AdminSongEdit"));
const AdminTags = lazy(() => import("./pages/admin/AdminTags"));
const Fallback = () => _jsx("div", { className: "detail-shell", children: "\uBD88\uB7EC\uC624\uB294 \uC911\u2026" });
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsxs(BrowserRouter, { children: [_jsx(Suspense, { fallback: _jsx(Fallback, {}), children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(SongList, {}) }), _jsx(Route, { path: "/megamix", element: _jsx(Megamix, {}) }), _jsx(Route, { path: "/songs/:id", element: _jsx(SongDetail, {}) }), _jsx(Route, { path: "/charts/:id", element: _jsx(ChartDetail, {}) }), _jsxs(Route, { path: "/admin", element: _jsx(AdminLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(AdminSongList, {}) }), _jsx(Route, { path: "songs/new", element: _jsx(AdminSongEdit, {}) }), _jsx(Route, { path: "songs/:id", element: _jsx(AdminSongEdit, {}) }), _jsx(Route, { path: "tags", element: _jsx(AdminTags, {}) })] }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }), _jsx(SpeedInsights, {}), _jsx(Analytics, {})] }) }));
