import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import SongList from "./pages/SongList";
import SongDetail from "./pages/SongDetail";
import ChartDetail from "./pages/ChartDetail";
import Megamix from "./pages/Megamix";
import AdminLayout from "./pages/admin/AdminLayout";
import AdminSongList from "./pages/admin/AdminSongList";
import AdminSongEdit from "./pages/admin/AdminSongEdit";
import AdminTags from "./pages/admin/AdminTags";
import "./styles/global.css";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(SongList, {}) }), _jsx(Route, { path: "/megamix", element: _jsx(Megamix, {}) }), _jsx(Route, { path: "/songs/:id", element: _jsx(SongDetail, {}) }), _jsx(Route, { path: "/charts/:id", element: _jsx(ChartDetail, {}) }), _jsxs(Route, { path: "/admin", element: _jsx(AdminLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(AdminSongList, {}) }), _jsx(Route, { path: "songs/new", element: _jsx(AdminSongEdit, {}) }), _jsx(Route, { path: "songs/:id", element: _jsx(AdminSongEdit, {}) }), _jsx(Route, { path: "tags", element: _jsx(AdminTags, {}) })] }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }) }));
